"""created inital

Revision ID: 45abbe55d0b8
Revises: 
Create Date: 2019-09-07 17:26:08.927735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45abbe55d0b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
